### ISSUE TITLE
are you still working on this project?

### ISSUE THREAD

**Issue by kashif0700444846** [Tindi12/Iced-Chat#1]
@Tindi12  I wanted to know if you are still working on this project?

**Comment by Tindi12** [comment]
Yes I have been planning some big updates to the UI and the signup page including some amazing features yet to be included.
:)

**Comment by kashif0700444846** [comment]
i wanted to suggest it will be great if there will be main room, every user
who joined with google or Facebook goes directly to that room and later if
user want user can create his own room and add other people into that room.
I am chat world user since 2012 so i have great experience about different
chat rooms.
